name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  build_release:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    name: build_release
    environment: Development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "container_tag=$(date +'%FT%H%M%SZ')" >> $GITHUB_ENV
      - uses: docker/login-action@v2
        with:
          registry: binkcore.azurecr.io
          username: binkcore
          password: ${{ secrets.ACR_BINKCORE_PASSWORD }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            binkcore.azurecr.io/${{ github.event.repository.name }}:${{ env.container_tag }}
            binkcore.azurecr.io/${{ github.event.repository.name }}:latest
