name: ci

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]
  release:
    types: [ published ]

jobs:
  build_dev_release:
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    name: build_dev_release
    environment: Development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "::set-output name=date::$(date +'%FT%H%M%SZ')"
        id: date
      - uses: docker/login-action@v1
        with:
          registry: binkcore.azurecr.io
          username: binkcore
          password: ${{ secrets.ACR_BINKCORE_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            binkcore.azurecr.io/${{ github.event.repository.name }}:${{ steps.date.outputs.date }}
            binkcore.azurecr.io/${{ github.event.repository.name }}:latest